### ISSUE TITLE
Informative Error On Pullup Error

### ISSUE THREAD

**Issue by jolynch** [MIT-Tab/mit-tab#39] opened 2014-04-12 22:51 UTC
We actually have an error for assigning pullups, but we don't throw it when that is the case, we should probably do that.

**Comment by BenMusch** [comment] 2019-03-24 23:51
I believe this is fixed by https://github.com/MIT-Tab/mit-tab/pull/121, because it prevented the cause of the error

**Closed by BenMusch** 2019-03-24 23:51 UTC
